using System;
using System.Collections.Generic;
using System.Text;
using TMPro;
using UnityEngine;
using UnityEngine.XR.MagicLeap;
using UnityEngine.InputSystem;
using PeterO.Cbor;

public class TripleTracker : MonoBehaviour
{
    public GameObject trackedObject;

    // marker settings
    // We no longer need a single hardcoded ID string since we track everything dynamically!
    private Dictionary<string, GameObject> _trackedMarkers = new Dictionary<string, GameObject>();
        
    // This was autogenerated and allows developers to create a dynamic
    // instance of an InputActionAsset which includes predefined action maps
    // that correspond to all of the Magic Leap 2's input.
    private MagicLeapInputs _magicLeapInputs;
    
    // This class is an Action Map and was autogenerated by the Unity Input
    // System and includes predefined bindings for the Magic Leap 2 Controller
    // Input Events.
    private MagicLeapInputs.ControllerActions _controllerActions;

    private bool _originFinding = true;

    private void Start()
    {
        //Debug.Log("OriginTracker::Start()");
        // create a tracker settings object with variables defined above
        MLMarkerTracker.ArucoDictionaryName d = MLMarkerTracker.ArucoDictionaryName.DICT_5X5_100;
        MLMarkerTracker.Profile profile = MLMarkerTracker.Profile.Accuracy;
        // create a tracker settings object with variables defined above
        MLMarkerTracker.TrackerSettings trackerSettings = MLMarkerTracker.TrackerSettings.Create(true, MLMarkerTracker.MarkerType.Aruco_April, 0.082f, d, 0.082f, profile);

       //Initialize the MagicLeapInputs like you would Unity's default action map.
       _magicLeapInputs = new MagicLeapInputs();
       _magicLeapInputs.Enable();
       //Initialize the ControllerActions based off the Magic Leap Input
       _controllerActions = new MagicLeapInputs.ControllerActions(_magicLeapInputs);
       _controllerActions.Trigger.started += HandleOnTriggerPull;
       _controllerActions.Trigger.canceled += HandleOnTriggerRelease;
       //_controllerActions.Bumper.performed += HandleOnBumper;
       _controllerActions.Bumper.canceled += HandleOnBumperRelease;

        trackedObject.SetActive(true);
        if (trackedObject.transform.childCount > 4)
        {
            trackedObject.transform.GetChild(4).gameObject.GetComponent<TextMeshPro>().text = "Release Trigger when aligned with the FLC ORIGIN";
        }

        // start marker tracking with tracker settings object
        _ = MLMarkerTracker.SetSettingsAsync(trackerSettings);
    }

    // subscribe to the event that detects markers
    private void OnEnable()
    {
        //Debug.Log("OriginTracker::OnEnable()");
        MLMarkerTracker.OnMLMarkerTrackerResultsFound += OnTrackerResultsFound;
    }

    // when the marker is detected...
    private void OnTrackerResultsFound(MLMarkerTracker.MarkerData data)
    {
        if (!_originFinding) return;

        if (data.Type == MLMarkerTracker.MarkerType.Aruco_April)
        {
            string detectedId = data.ArucoData.Id.ToString();
            
            //Debug.Log("OriginTracker Detected " + detectedId + " " + _controllerActions.Trigger.ReadValue<float>());
            //Debug.Log("OriginTracker updating " + detectedId + " " + data.Pose.position);

            Vector3 markerPos = data.Pose.position; // - new Vector3(0.0381f, 0.0f, -0.0381f);
            // Rotate the incoming pose to properly align real world orientation with virtual space
            Quaternion markerRot = data.Pose.rotation * Quaternion.Euler(-90, 0, 180);

            // Update visual trackers inside Unity
            UpdateVisualMarkerInUnity(detectedId, markerPos, markerRot);

            // Transmit data to Godot
            SendMarkerUpdateToGodot(detectedId, markerPos, markerRot);
        }
    }

    private void UpdateVisualMarkerInUnity(string id, Vector3 pos, Quaternion rot)
    {
        if (!_trackedMarkers.ContainsKey(id))
        {
            GameObject newMarkerObj = Instantiate(trackedObject, pos, rot);
            newMarkerObj.name = "Marker_" + id;
            
            if (newMarkerObj.transform.childCount > 4)
            {
                newMarkerObj.transform.GetChild(4).gameObject.SetActive(true);
                var textMesh = newMarkerObj.transform.GetChild(4).GetComponent<TextMeshPro>();
                if (textMesh != null) textMesh.text = "ID: " + id;
            }
            
            _trackedMarkers.Add(id, newMarkerObj);
        }
        else
        {
            _trackedMarkers[id].transform.position = pos;
            _trackedMarkers[id].transform.rotation = rot;
            _trackedMarkers[id].SetActive(true);
        }
    }

    private void SendMarkerUpdateToGodot(string id, Vector3 relativePos, Quaternion relativeRot)
    {
        try
        {
            var n_root = GameObject.FindWithTag("NoodlesRootItem");
            if (n_root != null)
            {
                var comp = n_root.GetComponent<NOODLESRoot>();
                if (comp != null)
                {
                    var args = new List<CBORObject>();
                    args.Add(CBORObject.FromObject(id)); 
                    args.Add(CBORObject.FromObject(relativePos));

                    // Send the components of the RELATIVE rotation
                    args.Add(CBORObject.FromObject(relativeRot.x));
                    args.Add(CBORObject.FromObject(relativeRot.y));
                    args.Add(CBORObject.FromObject(relativeRot.z));
                    args.Add(CBORObject.FromObject(relativeRot.w));

                    // Invoke our multi-tracker handler method on the server side
                    comp.invoke_method_by_name("multi_position_updated", args, NoReply);
                }
            }
        }
        catch (Exception e)
        {
            Debug.LogException(e);
        }
    }

    // Handles the event for the Trigger.
    private void HandleOnTriggerPull(InputAction.CallbackContext obj)
    {
        float triggerValue = obj.ReadValue<float>();
        //Debug.Log("OriginTracker: Pull. The Trigger value is : " +  triggerValue);
        if (trackedObject.transform.childCount > 4) trackedObject.transform.GetChild(4).gameObject.SetActive(true);
        _originFinding = true;
    }
    
    private void HandleOnTriggerRelease(InputAction.CallbackContext obj)
    {
        float triggerValue = obj.ReadValue<float>();
        //Debug.Log("OriginTracker: Release. The Trigger value is : " +  triggerValue);
        if (trackedObject.transform.childCount > 4) trackedObject.transform.GetChild(4).gameObject.SetActive(false);
        _originFinding = false;
    }

    private void Update()
    {
        if (_controllerActions.Bumper.IsPressed())
        {
            var controllerPosition = _controllerActions.Position.ReadValue<Vector3>();
            var controllerRotation = _controllerActions.Rotation.ReadValue<Quaternion>();
            //Debug.Log("OriginTracker Controller: " + controllerPosition + " " + controllerRotation);

            try
            {
                var n_root = GameObject.FindWithTag("NoodlesRootItem");
                if (n_root)
                {
                    var rootTransform = n_root.transform;
                    var inverseRootRotation = Quaternion.Inverse(rootTransform.rotation);

                    var relativePos = inverseRootRotation * (controllerPosition - rootTransform.position);
                    var relativeRot = inverseRootRotation * controllerRotation;

                    var args = new List<CBORObject>();
                    args.Add(CBORObject.FromObject(relativePos));

                    // Send the components of the RELATIVE rotation, not the absolute one.
                    args.Add(CBORObject.FromObject(relativeRot.x));
                    args.Add(CBORObject.FromObject(relativeRot.y));
                    args.Add(CBORObject.FromObject(relativeRot.z));
                    args.Add(CBORObject.FromObject(relativeRot.w));

                    var comp = n_root.GetComponent<NOODLESRoot>();
                    if (comp != null)
                    {
                        comp.invoke_method_by_name("position_updated", args, NoReply);
                    }
                }
            }
            catch (Exception e)
            {
                Debug.LogException(e);
            }
        }
    }

    private void HandleOnBumperRelease(InputAction.CallbackContext obj)
    {
        bool bumperDown = obj.ReadValueAsButton();
        //Debug.Log("OriginTracker The Bumper released " + bumperDown);

        try 
        {
            var n_root = GameObject.FindWithTag("NoodlesRootItem");

            if (n_root) {
                var args = new List<CBORObject>();
                var comp = n_root.GetComponent<NOODLESRoot>();

                if (comp != null)
                {
                    //Debug.Log("OriginTracker: INVOKE position_set");
                    comp.invoke_method_by_name("position_set",  args, NoReply);
                }                        
            }
        }
        catch (Exception e) 
        {
            Debug.LogException(e);
        }
    }

    private void NoReply(CBORObject reply) {
    }
}